# Generated by Django 4.2.24 on 2025-09-15 18:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("proveedor", models.CharField(max_length=40)),
                ("transaction_id", models.CharField(max_length=80, unique=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_pago", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AUTORIZADO", "Autorizado"),
                            ("CAPTURADO", "Capturado"),
                            ("FALLIDO", "Fallido"),
                            ("REEMBOLSADO", "Reembolsado"),
                        ],
                        default="AUTORIZADO",
                        max_length=12,
                    ),
                ),
                (
                    "orden",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pago",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
