# Generated by Django 4.2.24 on 2025-09-15 19:37

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="catalog_cat_slug_695af4_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["nombre"], name="catalog_cat_nombre_162a0b_idx"),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["sku"], name="catalog_inv_sku_84ab5e_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="catalog_pro_slug_2b1eb6_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["activo"], name="catalog_pro_activo_0ca3e2_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["categoria", "activo"], name="catalog_pro_categor_bfe3af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="catalog_pro_created_eee82f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug"),
                name="uniq_category_slug_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                check=models.Q(("stock__gte", 0)), name="inv_stock_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                check=models.Q(("reservado__gte", 0)), name="inv_reservado_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                check=models.Q(("reservado__lte", models.F("stock"))),
                name="inv_reservado_lte_stock",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("precio__gte", 0)), name="product_precio_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug"),
                name="uniq_product_slug_ci",
            ),
        ),
    ]
