# Generated by Django 4.2.24 on 2025-09-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_catalog_cat_slug_695af4_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["nombre"]},
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="uniq_category_slug_ci",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="catalog_cat_slug_695af4_idx",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="catalog_cat_nombre_162a0b_idx",
        ),
    ]
