# Generated by Django 4.2.24 on 2025-09-16 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RenameField(
            model_name="cartitem",
            old_name="carrito",
            new_name="cart",
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="cart",
            name="status",
        ),
        migrations.AddField(
            model_name="cart",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ABIERTO", "Abierto"),
                    ("BLOQUEADO", "Bloqueado"),
                    ("EXPIRADO", "Expirado"),
                ],
                default="ABIERTO",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="cart",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.product"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "producto")},
        ),
    ]
