# Generated by Django 4.2.24 on 2025-09-16 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_estado_order_delivered_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="fecha_pago",
        ),
        migrations.AddField(
            model_name="payment",
            name="captured_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="reserved_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="payment",
            name="monto",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="orden",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("AUTORIZADO", "Autorizado"),
                    ("CAPTURADO", "Capturado"),
                    ("FALLIDO", "Fallido"),
                    ("REEMBOLSADO", "Reembolsado"),
                ],
                default="AUTORIZADO",
                max_length=12,
            ),
        ),
    ]
