# Generated by Django 4.2.24 on 2025-09-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_payment_fecha_pago_payment_captured_applied_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_carrier",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("AUTORIZADO", "Autorizado"),
                    ("CAPTURADO", "Capturado"),
                    ("FALLIDO", "Fallido"),
                    ("REEMBOLSADO", "Reembolsado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="AUTORIZADO",
                max_length=12,
            ),
        ),
    ]
